#
# Basic CI to build and publish ATD's docker images
#

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master or production branch
on:
  push:
    branches:
    - master
    - production

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: "Checkout"
      uses: actions/checkout@v2

    # Runs a set of commands using the runners shell
    - name: Build & Publish Container
      env:
        ATD_DOCKER_USER: ${{ secrets.ATD_DOCKER_USER }}
        ATD_DOCKER_PASS: ${{ secrets.ATD_DOCKER_PASS }}
      run: |
        export BRANCH_NAME=${GITHUB_REF##*/}
        source ./.github/workflows/docker-helper.sh
        build_container
